[tool.poetry]
name = "eds-rene"
version = "0.1.0"
description = ""
authors = ["pidoux7 <faure.guillaume75@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
edsnlp = {extras = ["ml"], version = "^0.11.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
